# Generated by Django 4.1.3 on 2022-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_foodsupplier_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodsupplier',
            options={'ordering': ('order', 'name'), 'verbose_name_plural': 'Dostawcy jedzenia'},
        ),
        migrations.AddField(
            model_name='foodsupplier',
            name='order',
            field=models.IntegerField(default=99, verbose_name='Kolejność'),
        ),
    ]
