# Generated by Django 4.1.3 on 2022-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_room_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                verbose_name="Numer telefonu",
            ),
        ),
    ]
