# Generated by Django 4.1.4 on 2022-12-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_alter_restaurant_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="restaurant",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.restaurant",
                verbose_name="Godziny otwarcia restauracji",
            ),
            preserve_default=False,
        ),
    ]
