# Generated by Django 4.1.4 on 2022-12-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_alter_filteradvantage_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="filter_food",
            new_name="filter_foods",
        ),
    ]
