# Generated by Django 4.1.4 on 2023-01-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_advertisement_alter_photo_image_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "ordering": ("date_start", "order"),
                "verbose_name_plural": "Reklamy",
            },
        ),
        migrations.AddField(
            model_name="advertisement",
            name="order",
            field=models.IntegerField(default=1, verbose_name="kolejność"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="link",
            field=models.URLField(verbose_name="Link do reklamy"),
        ),
    ]
